import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Cinzel, Chivo } from "next/font/google"; // 👈 add these
import "./globals.css";
import { Navbar } from "@/layouts/navbar";
import Footer from "@/layouts/footer";
import { CartProvider } from "@/contexts/cart-provider";
import { OrderProvider } from "@/contexts/order-context";
import { CartButton } from "@/components/cart/cart-button";
import { ContactButton } from "@/layouts/contact-button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ["400", "700"], // pick weights you need
});

const chivo = Chivo({
  variable: "--font-chivo",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${cinzel.variable} 
          ${chivo.variable} 
          antialiased
        `}
      >
        <OrderProvider>
          <CartProvider>
            <CartButton />
            <Navbar />
            {children}
            <ContactButton />
            <Footer />
          </CartProvider>
        </OrderProvider>
      </body>
    </html>
  );
}
